libcfp: cfp::Parser Class Reference
cfp::Parser Class Reference
Parser implementation data structure.
#include <cfp.h>
Public Member Functions
Parser (void)
Default constructor.
Parser (const char *formula, const size_t len)
Constructor.
Parser (const Parser &p)
Copy constructor.
~Parser ()
Destructor.
void setFormula (const char *formula, const size_t len)
Sets the input formula of this Parser.
void setFormula (const std::string &formula)
Sets the input formula of this Parser.
const std::string & formula () const
Returns the current formula of this Parser.
void process (void)
Parses the current formula of this Parser.
const Compound & process (const char *formula, const size_t len)
Parses the given formula and returns the result.
const Compound & empirical (void) const
Returns the result of the most recent parsing operation.
std::string toMarkup (void) const
String representation of the parsed Formula with markup text formatting.
void setMaxNestingLevel (size_t lvl)
Sets the maximum nesting level within the supplied formulas.
size_t maxNestingLevel (void) const
Returns the maximum nesting level within the supplied formulas.
Private Attributes
ParserState * mD
Implementation data.
Detailed Description
Parser implementation data structure.
Parsing takes place here.
For input it takes the chemical formula in ASCII notation.
Parser(const char *, const size_t),
setFormula(const char *, const size_t),
setFormula(const std::string&),
process(const char *, const size_t)
For output it provides a list of CompoundElement objects which represents the empirical chemical formula (each element or isotope of an element occurs only once)
process(const char *, const size_t),
empirical()
Definition at line 322 of file cfp.h.
Constructor & Destructor Documentation
Parser::Parser (void)
Default constructor.
Definition at line 34 of file parser.cpp.
Parser::Parser (const char * formula, const size_t len)
Constructor.
Parameters:
[in] formula Chemical formula in ASCII notation.
[in] len Number of characters in formula.
Definition at line 39 of file parser.cpp.
References mD, and cfp::ParserState::reset().
Parser::Parser (const Parser & p)
Copy constructor.
Parameters:
[in] p Parser to copy all data from.
Definition at line 45 of file parser.cpp.
Parser::~Parser ()
Destructor.
Definition at line 50 of file parser.cpp.
References mD.
Member Function Documentation
const Compound & Parser::empirical (void) const
Returns the result of the most recent parsing operation.
Returns:
The empirical representation of the supplied formula.
Definition at line 87 of file parser.cpp.
References cfp::ElementGroup::flatList(), mD, and cfp::ParserState::rootGroup.
Referenced by process().
const std::string & Parser::formula () const
Returns the current formula of this Parser.
Definition at line 68 of file parser.cpp.
References cfp::ParserState::formula, and mD.
size_t Parser::maxNestingLevel (void) const
Returns the maximum nesting level within the supplied formulas.
See also:
setMaxNestingLevel
Definition at line 81 of file parser.cpp.
References cfp::ParserState::maxNestingLevel, and mD.
void Parser::process (void)
Parses the current formula of this Parser.
The result can be obtained by calling empirical().
Note:
May throw a cfp::Error or any of its sub-classes.
See also:
process(const char *, const size_t)
Definition at line 101 of file parser.cpp.
References cfp::ElementGroup::flatten(), cfp::ParserState::formula, mD, cfp::ParserState::parse(), and cfp::ParserState::rootGroup.
Referenced by process().
const Compound & Parser::process (const char * formula, const size_t len)
Parses the given formula and returns the result.
Provided for convenience.
Note:
May throw a cfp::Error or any of its sub-classes.
Parameters:
[in] formula The new input formula C-style string.
[in] len Number of characters in formula.
Returns:
The empirical representation of the supplied formula.
See also:
setFormula, process, empirical
Definition at line 93 of file parser.cpp.
References empirical(), process(), and setFormula().
void Parser::setFormula (const char * formula, const size_t len)
Sets the input formula of this Parser.
Parameters:
[in] formula The new input formula C-style string.
[in] len Number of characters in formula.
Definition at line 62 of file parser.cpp.
References mD, and cfp::ParserState::reset().
Referenced by process().
void Parser::setFormula (const std::string & formula)
Sets the input formula of this Parser.
Provided for convenience.
Parameters:
[in] formula The new input formula string.
Definition at line 56 of file parser.cpp.
References mD, and cfp::ParserState::reset().
void Parser::setMaxNestingLevel (size_t lvl)
Sets the maximum nesting level within the supplied formulas.
If a formula is processed which contains more nested parentheses (groups) than specified, an ErrorMaxNesting is thrown during Parser::process. The default is 30.
Parameters:
[in] lvl The maximum nesting level.
See also:
maxNestingLevel
Definition at line 74 of file parser.cpp.
References cfp::ParserState::curNestingLevel, cfp::ParserState::maxNestingLevel, and mD.
std::string Parser::toMarkup (void) const
String representation of the parsed Formula with markup text formatting.
This includes <sup> for the nucleon number and <sub> for the coefficient value.
Returns:
The formatted string.
Definition at line 110 of file parser.cpp.
References mD, and cfp::ParserState::rootGroup.
Field Documentation
ParserState* cfp::Parser::mD [private]
Implementation data.
Definition at line 391 of file cfp.h.
Referenced by empirical(), formula(), maxNestingLevel(), Parser(), process(), setFormula(), setMaxNestingLevel(), toMarkup(), and ~Parser().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/include/cfp/cfp.h
/home/ingo/code/libcfp/berlios/trunk/src/parser.cpp