libcfp: cfp::ChemicalElement Class Reference
cfp::ChemicalElement Class Reference
Implementation data structure.
#include <cfp.h>
Public Member Functions
ChemicalElement ()
Default constructor.
ChemicalElement (const ChemicalElement &eb)
Copy constructor.
ChemicalElement (const ChemicalElementInterface &eb)
Copy constructor for related elements.
virtual ~ChemicalElement ()
Destructor.
Private Member Functions
virtual std::string doSymbol (void) const
Specific implementation of ChemicalElementInterface::doSymbol.
virtual void doSetSymbol (const std::string &symbol)
Specific implementation of ChemicalElementInterface::doSetSymbol.
virtual int doNucleons (void) const
Specific implementation of ChemicalElementInterface::doNucleons.
virtual void doSetNucleons (int i)
Specific implementation of ChemicalElementInterface::doSetNucleons.
Private Attributes
ChemicalElementData * mD
Implementation data.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &o, const cfp::ChemicalElementInterface &e)
Writes the string representation of an ChemicalElement to an output stream.
Detailed Description
Implementation data structure.
A concrete chemical element descriptor implementation.
See also:
ChemicalElementInterface
Definition at line 220 of file cfp.h.
Constructor & Destructor Documentation
ChemicalElement::ChemicalElement ()
Default constructor.
Definition at line 191 of file element.cpp.
ChemicalElement::ChemicalElement (const ChemicalElement & eb)
Copy constructor.
Definition at line 196 of file element.cpp.
ChemicalElement::ChemicalElement (const ChemicalElementInterface & eb) [explicit]
Copy constructor for related elements.
Definition at line 201 of file element.cpp.
References cfp::ChemicalElementInterface::nucleons(), cfp::ChemicalElementInterface::setNucleons(), cfp::ChemicalElementInterface::setSymbol(), and cfp::ChemicalElementInterface::symbol().
ChemicalElement::~ChemicalElement () [virtual]
Destructor.
Definition at line 209 of file element.cpp.
References mD.
Member Function Documentation
int ChemicalElement::doNucleons (void) const [private, virtual]
Specific implementation of ChemicalElementInterface::doNucleons.
Implements cfp::ChemicalElementInterface.
Definition at line 228 of file element.cpp.
References mD, and cfp::ChemicalElementData::nucleons.
void ChemicalElement::doSetNucleons (int i) [private, virtual]
Specific implementation of ChemicalElementInterface::doSetNucleons.
Implements cfp::ChemicalElementInterface.
Definition at line 234 of file element.cpp.
References mD, and cfp::ChemicalElementData::nucleons.
void ChemicalElement::doSetSymbol (const std::string & symbol) [private, virtual]
Specific implementation of ChemicalElementInterface::doSetSymbol.
Implements cfp::ChemicalElementInterface.
Definition at line 222 of file element.cpp.
References mD, and cfp::ChemicalElementData::symbol.
std::string ChemicalElement::doSymbol (void) const [private, virtual]
Specific implementation of ChemicalElementInterface::doSymbol.
Implements cfp::ChemicalElementInterface.
Definition at line 216 of file element.cpp.
References mD, and cfp::ChemicalElementData::symbol.
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & o, const cfp::ChemicalElementInterface & e) [related]
Writes the string representation of an ChemicalElement to an output stream.
Parameters:
[in,out] o Output stream to write to.
[in] e ChemicalElement to create a string representation from.
Returns:
The output stream o.
Definition at line 398 of file element.cpp.
Field Documentation
ChemicalElementData* cfp::ChemicalElement::mD [private]
Implementation data.
Definition at line 251 of file cfp.h.
Referenced by doNucleons(), doSetNucleons(), doSetSymbol(), doSymbol(), and ~ChemicalElement().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/include/cfp/cfp.h
/home/ingo/code/libcfp/berlios/trunk/src/element.cpp