libcfp: cfp::CompoundElement Class Reference
cfp::CompoundElement Class Reference
A concrete compound element descriptor implementation.
#include <cfp.h>
Public Member Functions
CompoundElement ()
Default constructor.
CompoundElement (const CompoundElement &e)
Copy constructor.
CompoundElement (const CompoundElementInterface &e)
Copy constructor for related elements.
virtual ~CompoundElement ()
Destructor.
Private Member Functions
virtual std::string doSymbol (void) const
Specific implementation of ChemicalElementInterface::doSymbol.
virtual void doSetSymbol (const std::string &symbol)
Specific implementation of ChemicalElementInterface::doSetSymbol.
virtual int doNucleons (void) const
Specific implementation of ChemicalElementInterface::doNucleons.
virtual void doSetNucleons (int i)
Specific implementation of ChemicalElementInterface::doSetNucleons.
virtual double doCoefficient (void) const
Specific implementation of CompoundElementInterface::doCoefficient.
virtual void doSetCoefficient (double coefficient)
Specific implementation of CompoundElementInterface::doSetCoefficient.
Private Attributes
CompoundElementData * mD
Implementation data.
Detailed Description
A concrete compound element descriptor implementation.
See also:
CompoundElementInterface
Definition at line 258 of file cfp.h.
Constructor & Destructor Documentation
CompoundElement::CompoundElement ()
Default constructor.
Definition at line 241 of file element.cpp.
CompoundElement::CompoundElement (const CompoundElement & e)
Copy constructor.
Definition at line 246 of file element.cpp.
CompoundElement::CompoundElement (const CompoundElementInterface & e) [explicit]
Copy constructor for related elements.
Definition at line 251 of file element.cpp.
References cfp::CompoundElementInterface::coefficient(), cfp::ChemicalElementInterface::nucleons(), cfp::CompoundElementInterface::setCoefficient(), cfp::ChemicalElementInterface::setNucleons(), cfp::ChemicalElementInterface::setSymbol(), and cfp::ChemicalElementInterface::symbol().
CompoundElement::~CompoundElement () [virtual]
Destructor.
Definition at line 260 of file element.cpp.
References mD.
Member Function Documentation
double CompoundElement::doCoefficient (void) const [private, virtual]
Specific implementation of CompoundElementInterface::doCoefficient.
Implements cfp::CompoundElementInterface.
Definition at line 291 of file element.cpp.
References cfp::CompoundElementData::coefficient, and mD.
int CompoundElement::doNucleons (void) const [private, virtual]
Specific implementation of ChemicalElementInterface::doNucleons.
Implements cfp::ChemicalElementInterface.
Definition at line 279 of file element.cpp.
References mD, and cfp::ChemicalElementData::nucleons.
void CompoundElement::doSetCoefficient (double coefficient) [private, virtual]
Specific implementation of CompoundElementInterface::doSetCoefficient.
Implements cfp::CompoundElementInterface.
Definition at line 297 of file element.cpp.
References cfp::CompoundElementData::coefficient, and mD.
void CompoundElement::doSetNucleons (int i) [private, virtual]
Specific implementation of ChemicalElementInterface::doSetNucleons.
Implements cfp::ChemicalElementInterface.
Definition at line 285 of file element.cpp.
References mD, and cfp::ChemicalElementData::nucleons.
void CompoundElement::doSetSymbol (const std::string & symbol) [private, virtual]
Specific implementation of ChemicalElementInterface::doSetSymbol.
Implements cfp::ChemicalElementInterface.
Definition at line 273 of file element.cpp.
References mD, and cfp::ChemicalElementData::symbol.
std::string CompoundElement::doSymbol (void) const [private, virtual]
Specific implementation of ChemicalElementInterface::doSymbol.
Implements cfp::ChemicalElementInterface.
Definition at line 267 of file element.cpp.
References mD, and cfp::ChemicalElementData::symbol.
Field Documentation
CompoundElementData* cfp::CompoundElement::mD [private]
Implementation data.
Definition at line 299 of file cfp.h.
Referenced by doCoefficient(), doNucleons(), doSetCoefficient(), doSetNucleons(), doSetSymbol(), doSymbol(), and ~CompoundElement().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/include/cfp/cfp.h
/home/ingo/code/libcfp/berlios/trunk/src/element.cpp