libcfp: cfp::ElementGroup Class Reference
cfp::ElementGroup Class Reference
The internal result of the parsing process.
#include <elementgroup.h>
Public Member Functions
ElementGroup ()
Creates an empty group.
size_t size () const
Returns the number of elements including group descriptors.
void clear ()
Clears internal data structures.
void addToken (ParserState &s)
Adds the current Token data to this element group.
void addSubgroup (const ElementGroup &subGrp, size_t strIdx)
Adds another element group.
const Compound & flatList (void) const
Returns the flat empirical formula representation.
void flatten (void)
Converts the tree structure into a flat element list.
Private Types
enum LastElementProperty {
SYMBOL_PROPERTY, NUCLEON_PROPERTY, COEFFICIENT_PROPERTY, GROUP_PROPERTY,
NO_PROPERTY
}
Property of an element which was set last during formula parsing.
typedef adobe::forest
< CompoundGroupElement > forest
Tree structure to represent a formula.
typedef forest::iterator fiterator
Regular iterator.
typedef
adobe::depth_fullorder_iterator
< boost::range_const_iterator
< forest >::type > diterator
Iterator with (tree) depth counter.
typedef void(ElementGroup::* ParseFunc)(ParserState &s)
The prototype of the function directly related to parsing.
Private Member Functions
bool empty () const
Returns true, if this group contains no elements.
CompoundGroupElement & back ()
Returns the last element added.
const CompoundGroupElement & back () const
Returns the last element added.
void add (const CompoundGroupElement &e)
Adds a new element to the tree.
void addGroup (const ElementGroup &eg)
Adds another element group.
void addTokenSymbol (ParserState &s)
Handles a symbol token.
void addTokenInt (ParserState &s)
Handles a natural number token.
void addTokenFloat (ParserState &s)
Handles a real number token.
void addTokenGroup (ParserState &s)
Handles a group token (does nothing).
void addTokenNone (ParserState &s)
Handles a undefined token (does nothing).
Private Attributes
forest mF
Tree data structure containing all CompoundGroupElement objects.
Compound mList
Flat empirical element list.
LastElementProperty mLastElementProperty
Remembers the last property which was set during formula parsing.
Static Private Attributes
static std::vector< ParseFunc > mAddTokenFunctions
Array of Functions to handle different Tokens based on their type.
Friends
std::ostream & std::operator<< (std::ostream &o, const ElementGroup &eg)
Detailed Description
The internal result of the parsing process.
A hierachical data structure based on adobe::forest. It represents the input formula string exactly. Because we don't want to introduce external dependencies to the Adobe Source Library, the result is converted to a flat empirical element list (flatten()). Alternative result types are possible too, of course, but not yet implemented.
Definition at line 67 of file elementgroup.h.
Member Typedef Documentation
typedef adobe::depth_fullorder_iterator< boost::range_const_iterator< forest >::type > cfp::ElementGroup::diterator [private]
Iterator with (tree) depth counter.
Definition at line 79 of file elementgroup.h.
typedef forest::iterator cfp::ElementGroup::fiterator [private]
Regular iterator.
Definition at line 74 of file elementgroup.h.
typedef adobe::forest<CompoundGroupElement> cfp::ElementGroup::forest [private]
Tree structure to represent a formula.
Definition at line 71 of file elementgroup.h.
typedef void(ElementGroup::* cfp::ElementGroup::ParseFunc)(ParserState &s) [private]
The prototype of the function directly related to parsing.
See also:
ElementGroup(), parse_details.cpp
Definition at line 83 of file elementgroup.h.
Member Enumeration Documentation
enum cfp::ElementGroup::LastElementProperty [private]
Property of an element which was set last during formula parsing.
Enumerator:
SYMBOL_PROPERTY
NUCLEON_PROPERTY
COEFFICIENT_PROPERTY
GROUP_PROPERTY
NO_PROPERTY
Definition at line 162 of file elementgroup.h.
Constructor & Destructor Documentation
ElementGroup::ElementGroup ()
Creates an empty group.
Definition at line 35 of file elementgroup.cpp.
References addTokenFloat(), addTokenGroup(), addTokenInt(), addTokenNone(), addTokenSymbol(), mAddTokenFunctions, and cfp::Token::TYPE_NONE.
Member Function Documentation
void ElementGroup::add (const CompoundGroupElement & e) [private]
Adds a new element to the tree.
Definition at line 81 of file elementgroup.cpp.
References mF.
Referenced by addTokenInt(), and addTokenSymbol().
void ElementGroup::addGroup (const ElementGroup & eg) [private]
Adds another element group.
It gets hierarchical here. Final layout:
 [ <e1>  <e2>  <e3>  <g> ]         <= this element group
                      |
             [ <ee1> <ee2> <ee3> ] <= subGrp
 <e*[0-9]+> are regular elements
 <g> is a CompoundGroupElement with isGroup==true
Definition at line 87 of file elementgroup.cpp.
References mF.
Referenced by addSubgroup().
void ElementGroup::addSubgroup (const ElementGroup & subGrp, size_t strIdx)
Adds another element group.
Some parsing related decisions are made here regarding nucleon numbers, respectively isotopes which are distinct element groups formally.
See also:
addGroup
Definition at line 98 of file parserdetails.cpp.
References addGroup(), back(), empty(), cfp::CompoundGroupElement::isGroup(), cfp::ChemicalElementInterface::isIsotope(), mLastElementProperty, cfp::ChemicalElementInterface::nucleons(), cfp::ChemicalElementInterface::setNucleons(), size(), and cfp::ChemicalElementInterface::symbol().
Referenced by cfp::ParserState::parseBracketO().
void ElementGroup::addToken (ParserState & s)
Adds the current Token data to this element group.
Eventually, creates a new CompoundElement from it or adds its data to the previous element.
Definition at line 36 of file parserdetails.cpp.
References cfp::Token::length(), mAddTokenFunctions, cfp::ParserState::token(), and cfp::Token::type.
Referenced by cfp::ParserState::parse(), cfp::ParserState::parseAlpha(), cfp::ParserState::parseBracketO(), cfp::ParserState::parseNumbers(), and cfp::ParserState::parseSpace().
void ElementGroup::addTokenFloat (ParserState & s) [private]
Handles a real number token.
Definition at line 71 of file parserdetails.cpp.
References back(), COEFFICIENT_PROPERTY, cfp::ParserState::curPos, empty(), cfp::Token::length(), mLastElementProperty, cfp::CompoundElementInterface::setCoefficient(), cfp::Token::toDouble(), and cfp::ParserState::token().
Referenced by ElementGroup().
void ElementGroup::addTokenGroup (ParserState & s) [private]
Handles a group token (does nothing).
Definition at line 88 of file parserdetails.cpp.
Referenced by ElementGroup().
void ElementGroup::addTokenInt (ParserState & s) [private]
Handles a natural number token.
Definition at line 57 of file parserdetails.cpp.
References add(), back(), COEFFICIENT_PROPERTY, empty(), mLastElementProperty, cfp::CompoundElementInterface::setCoefficient(), cfp::ChemicalElementInterface::setNucleons(), cfp::Token::toDouble(), cfp::Token::toInt(), and cfp::ParserState::token().
Referenced by ElementGroup().
void ElementGroup::addTokenNone (ParserState & s) [private]
Handles a undefined token (does nothing).
Definition at line 93 of file parserdetails.cpp.
Referenced by ElementGroup().
void ElementGroup::addTokenSymbol (ParserState & s) [private]
Handles a symbol token.
Definition at line 43 of file parserdetails.cpp.
References add(), back(), empty(), mLastElementProperty, cfp::ChemicalElementInterface::setSymbol(), cfp::ParserState::token(), and cfp::Token::toString().
Referenced by ElementGroup().
CompoundGroupElement & ElementGroup::back () [private]
Returns the last element added.
Definition at line 69 of file elementgroup.cpp.
References mF.
Referenced by addSubgroup(), addTokenFloat(), addTokenInt(), and addTokenSymbol().
const CompoundGroupElement & ElementGroup::back () const [private]
Returns the last element added.
Definition at line 75 of file elementgroup.cpp.
References mF.
void ElementGroup::clear ()
Clears internal data structures.
Definition at line 62 of file elementgroup.cpp.
References mF, and mList.
Referenced by cfp::ParserState::reset().
bool ElementGroup::empty () const [private]
Returns true, if this group contains no elements.
Definition at line 56 of file elementgroup.cpp.
References mF.
Referenced by addSubgroup(), addTokenFloat(), addTokenInt(), and addTokenSymbol().
const Compound & ElementGroup::flatList (void) const
Returns the flat empirical formula representation.
Definition at line 96 of file elementgroup.cpp.
References mList.
Referenced by cfp::Parser::empirical().
void ElementGroup::flatten (void)
Converts the tree structure into a flat element list.
Definition at line 123 of file elementgroup.cpp.
References addToSet(), cfp::CompoundElementInterface::coefficient(), mF, mList, and cfp::CompoundElementInterface::setCoefficient().
Referenced by cfp::Parser::process().
size_t ElementGroup::size () const
Returns the number of elements including group descriptors.
Definition at line 50 of file elementgroup.cpp.
References mF.
Referenced by addSubgroup().
Friends And Related Function Documentation
std::ostream& std::operator<< (std::ostream & o, const ElementGroup & eg) [friend]
Field Documentation
std::vector< ElementGroup::ParseFunc > ElementGroup::mAddTokenFunctions [static, private]
Array of Functions to handle different Tokens based on their type.
Definition at line 158 of file elementgroup.h.
Referenced by addToken(), and ElementGroup().
forest cfp::ElementGroup::mF [private]
Tree data structure containing all CompoundGroupElement objects.
Definition at line 151 of file elementgroup.h.
Referenced by add(), addGroup(), back(), clear(), empty(), flatten(), std::operator<<(), and size().
LastElementProperty cfp::ElementGroup::mLastElementProperty [private]
Remembers the last property which was set during formula parsing.
Used to tell adjacent nucleon and coefficient numbers apart.
Definition at line 173 of file elementgroup.h.
Referenced by addSubgroup(), addTokenFloat(), addTokenInt(), and addTokenSymbol().
Compound cfp::ElementGroup::mList [private]
Flat empirical element list.
Definition at line 154 of file elementgroup.h.
Referenced by clear(), flatList(), and flatten().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/src/elementgroup.h
/home/ingo/code/libcfp/berlios/trunk/src/elementgroup.cpp
/home/ingo/code/libcfp/berlios/trunk/src/parserdetails.cpp