libcfp: cfp::ChemicalElementInterface Class Reference
cfp::ChemicalElementInterface Class Reference
Representation of a generic chemical element.
#include <cfp.h>
Public Member Functions
virtual ~ChemicalElementInterface ()
Destructor.
std::string symbol (void) const
Returns the symbol.
void setSymbol (const std::string &s)
Sets the symbol.
int nucleons (void) const
Returns the nucleon number.
void setNucleons (int i)
Sets the nucleon number.
bool isIsotope (void) const
Identifies an CompoundElement as isotope or natural element.
std::string uniqueName (void) const
Unique string representation of this element.
std::string toString (void) const
String representation of this element.
std::string toMarkup (void) const
String representation with markup text formatting.
bool operator< (const ChemicalElementInterface &e) const
Compares two elements lexically.
ChemicalElementInterface & operator= (const ChemicalElementInterface &e)
Copies element data.
Static Public Member Functions
static const int naturalNucleonNr ()
Returns the default nucleon number.
Protected Member Functions
virtual std::string doUniqueName (void) const
Unique name implementation for a generic element.
virtual std::string doToString (void) const
String (ASCII) conversion for a generic element.
virtual std::string doToMarkup (void) const
Formatted string (HTML) conversion for a generic element.
Private Member Functions
virtual std::string doSymbol (void) const =0
Data read access for the symbol.
virtual void doSetSymbol (const std::string &symbol)=0
Data write access for the symbol.
virtual int doNucleons (void) const =0
Data read access for the nucleon number.
virtual void doSetNucleons (int i)=0
Data write access for the nucleon number.
Detailed Description
Representation of a generic chemical element.
It consists of:
A symbol which identifies the chemical element it represents.
See also:
setSymbol, symbol
A nucleon number (also called atomic mass number) which identifies this element as a specific isotope. The default nucleon number is the same (invalid) number for all elements (naturalNucleonNr()).
See also:
setNucleon, nucleon, isIsotope
Definition at line 50 of file cfp.h.
Constructor & Destructor Documentation
ChemicalElementInterface::~ChemicalElementInterface () [virtual]
Destructor.
Definition at line 42 of file element.cpp.
Member Function Documentation
virtual int cfp::ChemicalElementInterface::doNucleons (void) const [private, pure virtual]
Data read access for the nucleon number.
Implemented in cfp::CompoundGroupElement, cfp::ChemicalElement, and cfp::CompoundElement.
Referenced by nucleons().
virtual void cfp::ChemicalElementInterface::doSetNucleons (int i) [private, pure virtual]
Data write access for the nucleon number.
Implemented in cfp::CompoundGroupElement, cfp::ChemicalElement, and cfp::CompoundElement.
Referenced by setNucleons().
virtual void cfp::ChemicalElementInterface::doSetSymbol (const std::string & symbol) [private, pure virtual]
Data write access for the symbol.
Implemented in cfp::CompoundGroupElement, cfp::ChemicalElement, and cfp::CompoundElement.
Referenced by setSymbol().
virtual std::string cfp::ChemicalElementInterface::doSymbol (void) const [private, pure virtual]
Data read access for the symbol.
Implemented in cfp::CompoundGroupElement, cfp::ChemicalElement, and cfp::CompoundElement.
Referenced by symbol().
std::string ChemicalElementInterface::doToMarkup (void) const [protected, virtual]
Formatted string (HTML) conversion for a generic element.
Reimplemented in cfp::CompoundElementInterface.
Definition at line 132 of file element.cpp.
References isIsotope(), nucleons(), and symbol().
Referenced by toMarkup().
std::string ChemicalElementInterface::doToString (void) const [protected, virtual]
String (ASCII) conversion for a generic element.
Reimplemented in cfp::CompoundElementInterface.
Definition at line 122 of file element.cpp.
References isIsotope(), nucleons(), and symbol().
Referenced by doUniqueName(), and toString().
std::string ChemicalElementInterface::doUniqueName (void) const [protected, virtual]
Unique name implementation for a generic element.
Definition at line 116 of file element.cpp.
References doToString().
Referenced by uniqueName().
bool ChemicalElementInterface::isIsotope (void) const
Identifies an CompoundElement as isotope or natural element.
Returns:
True, if this element is an isotope. False, if it is a regular element.
See also:
setNucleon, nucleon, naturalNucleonNr
Definition at line 72 of file element.cpp.
References naturalNucleonNr(), and nucleons().
Referenced by cfp::ElementGroup::addSubgroup(), doToMarkup(), cfp::CompoundElementInterface::doToString(), and doToString().
const int ChemicalElementInterface::naturalNucleonNr () [static]
Returns the default nucleon number.
It is assigned to all elements which are considered to be not an isotope but a natural element which consists of a mixture of stable isotopes. It is an invalid number (negative).
See also:
setNucleon, nucleon, isIsotope
Definition at line 37 of file element.cpp.
Referenced by isIsotope(), and setNucleons().
int ChemicalElementInterface::nucleons (void) const
Returns the nucleon number.
See also:
setNucleon, isIsotope, naturalNucleonNr
Definition at line 59 of file element.cpp.
References doNucleons().
Referenced by cfp::ElementGroup::addSubgroup(), cfp::ChemicalElement::ChemicalElement(), cfp::CompoundElement::CompoundElement(), doToMarkup(), doToString(), isIsotope(), operator<(), and operator=().
bool ChemicalElementInterface::operator< (const ChemicalElementInterface & e) const
Compares two elements lexically.
First, it compares the names of both elements. If the names are identical, the element with a lower nucleon number is less than the other element.
Parameters:
[in] e The element to compare this element with.
Returns:
True, if this element is less than the other provided element. False, otherwise.
Definition at line 96 of file element.cpp.
References nucleons(), and symbol().
ChemicalElementInterface & ChemicalElementInterface::operator= (const ChemicalElementInterface & e)
Copies element data.
Parameters:
[in] e The element to copy data from.
Returns:
A reference to this element.
Definition at line 106 of file element.cpp.
References nucleons(), setNucleons(), setSymbol(), and symbol().
void ChemicalElementInterface::setNucleons (int i)
Sets the nucleon number.
Parameters:
[in] i The new nucleon number.
See also:
nucleon, isIsotope, naturalNucleonNr
Definition at line 65 of file element.cpp.
References doSetNucleons(), and naturalNucleonNr().
Referenced by cfp::ElementGroup::addSubgroup(), cfp::ElementGroup::addTokenInt(), cfp::ChemicalElement::ChemicalElement(), cfp::CompoundElement::CompoundElement(), and operator=().
void ChemicalElementInterface::setSymbol (const std::string & s)
Sets the symbol.
Parameters:
[in] s The new symbol of the element.
See also:
symbol
Definition at line 53 of file element.cpp.
References doSetSymbol().
Referenced by cfp::ElementGroup::addTokenSymbol(), cfp::ChemicalElement::ChemicalElement(), cfp::CompoundElement::CompoundElement(), and operator=().
std::string ChemicalElementInterface::symbol (void) const
Returns the symbol.
See also:
setSymbol
Definition at line 47 of file element.cpp.
References doSymbol().
Referenced by cfp::ElementGroup::addSubgroup(), cfp::ChemicalElement::ChemicalElement(), cfp::CompoundElement::CompoundElement(), doToMarkup(), doToString(), operator<(), and operator=().
std::string ChemicalElementInterface::toMarkup (void) const
String representation with markup text formatting.
This includes <sup> for the nucleon number and <sub> for the coefficient value.
Returns:
The formatted string.
Definition at line 90 of file element.cpp.
References doToMarkup().
std::string ChemicalElementInterface::toString (void) const
String representation of this element.
Builds a string with the symbol preceded by the nucleon number (if it is an isotope).
Definition at line 84 of file element.cpp.
References doToString().
Referenced by std::operator<<().
std::string ChemicalElementInterface::uniqueName (void) const
Unique string representation of this element.
Same as toString() but will not be overridden by subclasses by default.
See also:
toString()
Definition at line 78 of file element.cpp.
References doUniqueName().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/include/cfp/cfp.h
/home/ingo/code/libcfp/berlios/trunk/src/element.cpp