libcfp: cfp::ParserState Class Reference
cfp::ParserState Class Reference
Implementation data of a Parser.
#include <parserstate.h>
Public Member Functions
ParserState ()
Initializes the data required for parsing.
void reset (const char *formula, const size_t len)
Prepares for parsing a new formula.
void parse (void)
Continues processing the current formula at this state.
void setToken (Token &t)
Updates the pointer to the current Token to use.
Token & token (void)
Returns the current Token used for parsing.
Data Fields
size_t maxNestingLevel
Maximum nesting level for element groups.
size_t curNestingLevel
Current nesting level during parsing.
size_t curPos
Current position within the formula.
std::string formula
Complete formula.
ElementGroup rootGroup
Hierarchical result structure.
Private Member Functions
void setCurrentGroup (ElementGroup &eg)
Updates the pointer to the current result group to use.
ElementGroup & currentGroup (void)
Returns the current result group used for parsing.
void parseNumbers (const char &c)
Handles numerical characters.
void parseDecimalOp (const char &c)
Handles decimal operators.
void parseAlpha (const char &c)
Handles Alphabetical characters.
void parseBracketO (const char &c)
Handles opening parentheses.
void parseBracketC (const char &c)
Handles closing parentheses.
void parseSpace (const char &c)
Handles ignored characters.
Private Attributes
ElementGroup * mCurGroup
Result structure for the current nesting level.
Token * mToken
Token for the current nesting level.
Detailed Description
Implementation data of a Parser.
Handling and processing of the input string is done here. It is also a container for all data structures required during the parse process.
Definition at line 40 of file parserstate.h.
Constructor & Destructor Documentation
ParserState::ParserState ()
Initializes the data required for parsing.
Definition at line 33 of file parserstate.cpp.
Member Function Documentation
ElementGroup & ParserState::currentGroup (void) [private]
Returns the current result group used for parsing.
Definition at line 72 of file parserstate.cpp.
References mCurGroup.
Referenced by parse(), parseAlpha(), parseBracketO(), parseNumbers(), and parseSpace().
void ParserState::parse (void)
Continues processing the current formula at this state.
Is called recursively with updated data pointers.
Todo:
Categorization of characters is done by conditional tests (if-else). An alternative would be a global, i.e. static, lookup table (std::vector or array) containing the appropriate handler function pointers for (125-40=85) relevant elements. Performance improvement or overkill ? Security issues ?
Definition at line 266 of file parserdetails.cpp.
References cfp::ElementGroup::addToken(), curNestingLevel, curPos, currentGroup(), formula, IS_ALPHA, IS_BRACKET_C, IS_BRACKET_O, IS_DECIM, IS_NUM, IS_SPACE, maxNestingLevel, parseAlpha(), parseBracketC(), parseBracketO(), parseDecimalOp(), parseNumbers(), parseSpace(), and setToken().
Referenced by parseBracketO(), and cfp::Parser::process().
void ParserState::parseAlpha (const char & c) [private]
Handles Alphabetical characters.
Definition at line 188 of file parserdetails.cpp.
References cfp::ElementGroup::addToken(), cfp::Token::append(), cfp::Token::clear(), curPos, currentGroup(), IS_ALPHA_L, token(), cfp::Token::type, and cfp::Token::TYPE_SYMBOL.
Referenced by parse().
void ParserState::parseBracketC (const char & c) [private]
Handles closing parentheses.
Definition at line 243 of file parserdetails.cpp.
References curNestingLevel, curPos, and maxNestingLevel.
Referenced by parse().
void ParserState::parseBracketO (const char & c) [private]
Handles opening parentheses.
Definition at line 212 of file parserdetails.cpp.
References cfp::ElementGroup::addSubgroup(), cfp::ElementGroup::addToken(), cfp::Token::clear(), curNestingLevel, curPos, currentGroup(), parse(), setCurrentGroup(), setToken(), token(), and cfp::Token::type.
Referenced by parse().
void ParserState::parseDecimalOp (const char & c) [private]
Handles decimal operators.
Definition at line 173 of file parserdetails.cpp.
References cfp::Token::append(), curPos, token(), cfp::Token::type, and cfp::Token::TYPE_INT.
Referenced by parse().
void ParserState::parseNumbers (const char & c) [private]
Handles numerical characters.
Definition at line 157 of file parserdetails.cpp.
References cfp::ElementGroup::addToken(), cfp::Token::append(), cfp::Token::clear(), currentGroup(), token(), cfp::Token::type, cfp::Token::TYPE_FLOAT, and cfp::Token::TYPE_SYMBOL.
Referenced by parse().
void ParserState::parseSpace (const char & c) [private]
Handles ignored characters.
Definition at line 252 of file parserdetails.cpp.
References cfp::ElementGroup::addToken(), cfp::Token::clear(), currentGroup(), token(), cfp::Token::type, cfp::Token::TYPE_FLOAT, cfp::Token::TYPE_INT, and cfp::Token::TYPE_SYMBOL.
Referenced by parse().
void ParserState::reset (const char * formula, const size_t len)
Prepares for parsing a new formula.
Removes all remaining data related to the previous formula
Definition at line 43 of file parserstate.cpp.
References cfp::ElementGroup::clear(), curNestingLevel, curPos, formula, maxNestingLevel, mCurGroup, and rootGroup.
Referenced by cfp::Parser::Parser(), and cfp::Parser::setFormula().
void ParserState::setCurrentGroup (ElementGroup & eg) [private]
Updates the pointer to the current result group to use.
Definition at line 66 of file parserstate.cpp.
References mCurGroup.
Referenced by parseBracketO().
void ParserState::setToken (Token & t)
Updates the pointer to the current Token to use.
Definition at line 54 of file parserstate.cpp.
References mToken.
Referenced by parse(), and parseBracketO().
Token & ParserState::token (void)
Returns the current Token used for parsing.
Definition at line 60 of file parserstate.cpp.
References mToken.
Referenced by cfp::ElementGroup::addToken(), cfp::ElementGroup::addTokenFloat(), cfp::ElementGroup::addTokenInt(), cfp::ElementGroup::addTokenSymbol(), parseAlpha(), parseBracketO(), parseDecimalOp(), parseNumbers(), and parseSpace().
Field Documentation
size_t cfp::ParserState::curNestingLevel
Current nesting level during parsing.
Definition at line 87 of file parserstate.h.
Referenced by parse(), parseBracketC(), parseBracketO(), reset(), and cfp::Parser::setMaxNestingLevel().
size_t cfp::ParserState::curPos
Current position within the formula.
Definition at line 88 of file parserstate.h.
Referenced by cfp::ElementGroup::addTokenFloat(), parse(), parseAlpha(), parseBracketC(), parseBracketO(), parseDecimalOp(), and reset().
std::string cfp::ParserState::formula
Complete formula.
Definition at line 89 of file parserstate.h.
Referenced by cfp::Parser::formula(), parse(), cfp::Parser::process(), and reset().
size_t cfp::ParserState::maxNestingLevel
Maximum nesting level for element groups.
Definition at line 86 of file parserstate.h.
Referenced by cfp::Parser::maxNestingLevel(), parse(), parseBracketC(), reset(), and cfp::Parser::setMaxNestingLevel().
ElementGroup* cfp::ParserState::mCurGroup [private]
Result structure for the current nesting level.
Definition at line 92 of file parserstate.h.
Referenced by currentGroup(), reset(), and setCurrentGroup().
Token* cfp::ParserState::mToken [private]
Token for the current nesting level.
Definition at line 93 of file parserstate.h.
Referenced by setToken(), and token().
ElementGroup cfp::ParserState::rootGroup
Hierarchical result structure.
Definition at line 90 of file parserstate.h.
Referenced by cfp::Parser::empirical(), cfp::Parser::process(), reset(), and cfp::Parser::toMarkup().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/src/parserstate.h
/home/ingo/code/libcfp/berlios/trunk/src/parserdetails.cpp
/home/ingo/code/libcfp/berlios/trunk/src/parserstate.cpp