libcfp: cfp::CompoundElementInterface Class Reference
cfp::CompoundElementInterface Class Reference
Representation of a chemical element within a compound.
#include <cfp.h>
Public Member Functions
virtual ~CompoundElementInterface ()
Destructor.
void setCoefficient (double coefficient)
Sets the coefficient value.
double coefficient (void) const
Returns the coefficient value.
CompoundElementInterface & operator= (const CompoundElementInterface &e)
Protected Member Functions
virtual std::string doToString (void) const
String representation of this element.
virtual std::string doToMarkup (void) const
String representation of this CompoundElement with markup text formatting.
Private Member Functions
virtual double doCoefficient (void) const =0
Data read access for coefficient value.
virtual void doSetCoefficient (double coefficient)=0
Data write access for coefficient value.
Detailed Description
Representation of a chemical element within a compound.
Besides of the properties a ChemicalElementInterface element consists of, this one has an additional property:
A coefficient value to specify the amount of this element in the overall compound, i.e. formula (as in H2).
See also:
setCoef, coef
Definition at line 168 of file cfp.h.
Constructor & Destructor Documentation
CompoundElementInterface::~CompoundElementInterface () [virtual]
Destructor.
Definition at line 143 of file element.cpp.
Member Function Documentation
double CompoundElementInterface::coefficient (void) const
Returns the coefficient value.
See also:
setCoef
Definition at line 154 of file element.cpp.
References doCoefficient().
Referenced by addToSet(), cfp::CompoundElement::CompoundElement(), doToMarkup(), doToString(), cfp::ElementGroup::flatten(), and operator=().
virtual double cfp::CompoundElementInterface::doCoefficient (void) const [private, pure virtual]
Data read access for coefficient value.
Implemented in cfp::CompoundGroupElement, and cfp::CompoundElement.
Referenced by coefficient().
virtual void cfp::CompoundElementInterface::doSetCoefficient (double coefficient) [private, pure virtual]
Data write access for coefficient value.
Implemented in cfp::CompoundGroupElement, and cfp::CompoundElement.
Referenced by setCoefficient().
std::string CompoundElementInterface::doToMarkup (void) const [protected, virtual]
String representation of this CompoundElement with markup text formatting.
This includes <sup> for the nucleon number and <sub> for the coefficient value.
Returns:
The formatted string.
Reimplemented from cfp::ChemicalElementInterface.
Definition at line 181 of file element.cpp.
References coefficient().
std::string CompoundElementInterface::doToString (void) const [protected, virtual]
String representation of this element.
Builds a string with the symbol preceded by the nucleon number (if it is an isotope) and followed by the compound coefficient.
Reimplemented from cfp::ChemicalElementInterface.
Definition at line 170 of file element.cpp.
References coefficient(), and cfp::ChemicalElementInterface::isIsotope().
CompoundElementInterface & CompoundElementInterface::operator= (const CompoundElementInterface & e)
See also:
ChemicalElementInterface::operator=
Definition at line 160 of file element.cpp.
References coefficient(), and setCoefficient().
void CompoundElementInterface::setCoefficient (double coefficient)
Sets the coefficient value.
Parameters:
[in] coefficient The new coefficient value.
See also:
coef
Definition at line 148 of file element.cpp.
References doSetCoefficient().
Referenced by cfp::ElementGroup::addTokenFloat(), cfp::ElementGroup::addTokenInt(), addToSet(), cfp::CompoundElement::CompoundElement(), cfp::CompoundGroupElement::CompoundGroupElement(), cfp::ElementGroup::flatten(), and operator=().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/include/cfp/cfp.h
/home/ingo/code/libcfp/berlios/trunk/src/element.cpp