libcfp: cfp::Token Class Reference
cfp::Token Class Reference
A group of adjacent characters with a special meaning within a formula string.
#include <token.h>
Public Types
enum Type {
TYPE_SYMBOL, TYPE_GROUP, TYPE_INT, TYPE_FLOAT,
TYPE_NONE
}
The type of a Token within a formula.
Public Member Functions
Token ()
Creates a Token with Token::TYPE_NONE.
void append (char c)
Appends a single character.
size_t length () const
Returns the length of this Token.
void clear ()
Clears this Token so that length() returns 0.
const std::string & toString () const
Returns the string representation of this Token.
int toInt () const
Returns the integer representation of this Token.
double toDouble () const
Return the floating point representation of this Token.
Data Fields
Type type
Its type.
Private Attributes
std::string mStr
The characters this token consists of.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &o, const cfp::ElementGroup &eg)
Writes the string representation of an ElementGroup to an output stream.
std::ostream & operator<< (std::ostream &o, const cfp::Token &t)
Writes the string representation of a Token to an output stream.
Detailed Description
A group of adjacent characters with a special meaning within a formula string.
Definition at line 36 of file token.h.
Member Enumeration Documentation
enum cfp::Token::Type
The type of a Token within a formula.
See also:
std::operator<<(std::ostream&, const cfp::Token::Type&)
Enumerator:
TYPE_SYMBOL
An element symbol.
TYPE_GROUP
A group characterized by parentheses.
TYPE_INT
A natural number.
TYPE_FLOAT
A real number.
TYPE_NONE
Nothing/Invalid.
Definition at line 41 of file token.h.
Constructor & Destructor Documentation
Token::Token ()
Creates a Token with Token::TYPE_NONE.
Definition at line 33 of file token.cpp.
Member Function Documentation
void Token::append (char c)
Appends a single character.
Parameters:
[in] c Character to append.
Definition at line 38 of file token.cpp.
References mStr.
Referenced by cfp::ParserState::parseAlpha(), cfp::ParserState::parseDecimalOp(), and cfp::ParserState::parseNumbers().
void Token::clear ()
Clears this Token so that length() returns 0.
Definition at line 48 of file token.cpp.
References mStr.
Referenced by cfp::ParserState::parseAlpha(), cfp::ParserState::parseBracketO(), cfp::ParserState::parseNumbers(), and cfp::ParserState::parseSpace().
size_t Token::length () const
Returns the length of this Token.
Returns:
Its length.
Definition at line 43 of file token.cpp.
References mStr.
Referenced by cfp::ElementGroup::addToken(), and cfp::ElementGroup::addTokenFloat().
double Token::toDouble () const
Return the floating point representation of this Token.
Returns:
This Token converted to a floating point number.
Definition at line 66 of file token.cpp.
References mStr.
Referenced by cfp::ElementGroup::addTokenFloat(), and cfp::ElementGroup::addTokenInt().
int Token::toInt () const
Returns the integer representation of this Token.
Returns:
This Token converted to an integer number.
Definition at line 58 of file token.cpp.
References mStr.
Referenced by cfp::ElementGroup::addTokenInt().
const std::string & Token::toString () const
Returns the string representation of this Token.
Returns:
A string consisting of all characters.
Definition at line 53 of file token.cpp.
References mStr.
Referenced by cfp::ElementGroup::addTokenSymbol(), and std::operator<<().
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & o, const cfp::ElementGroup & eg) [related]
Writes the string representation of an ElementGroup to an output stream.
Returns the string representation of this ElementGroup with markup text formatting (<sup>, <sub>).
Parameters:
[in,out] o Output stream to write to.
[in] eg ElementGroup to create a string representation from.
Returns:
The output stream o.
Definition at line 165 of file elementgroup.cpp.
std::ostream & operator<< (std::ostream & o, const cfp::Token & t) [related]
Writes the string representation of a Token to an output stream.
Parameters:
[in,out] o Output stream to write to.
[in] t Token to create a string representation from.
Returns:
The output stream o.
Definition at line 96 of file token.cpp.
Field Documentation
std::string cfp::Token::mStr [private]
The characters this token consists of.
Definition at line 83 of file token.h.
Referenced by append(), clear(), length(), toDouble(), toInt(), and toString().
Type cfp::Token::type
Its type.
See also:
Token::Type
Definition at line 81 of file token.h.
Referenced by cfp::ElementGroup::addToken(), std::operator<<(), cfp::ParserState::parseAlpha(), cfp::ParserState::parseBracketO(), cfp::ParserState::parseDecimalOp(), cfp::ParserState::parseNumbers(), and cfp::ParserState::parseSpace().
The documentation for this class was generated from the following files:
/home/ingo/code/libcfp/berlios/trunk/src/token.h
/home/ingo/code/libcfp/berlios/trunk/src/elementgroup.h
/home/ingo/code/libcfp/berlios/trunk/src/token.cpp