libcfp: /home/ingo/code/libcfp/berlios/trunk/src/elementgroup.cpp File Reference
elementgroup.cpp File Reference
#include <set>
#include "parserstate.h"
Typedefs
typedef std::set< CompoundElement > Set
Functions
void addToSet (Set &s, CompoundElement &e)
Typedef Documentation
typedef std::set<CompoundElement> Set
Definition at line 102 of file elementgroup.cpp.
Function Documentation
void addToSet (Set & s, CompoundElement & e)
Definition at line 105 of file elementgroup.cpp.
References cfp::CompoundElementInterface::coefficient(), and cfp::CompoundElementInterface::setCoefficient().
Referenced by cfp::ElementGroup::flatten().